name: dbt_jev_example
version: 0.1.0
config-version: 2
profile: dbt_jev_example

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  dbt_jev_example:
    +materialized: table

